package ca.ulaval.glo4002.application.domain.event;

public enum SecurityEventName{
  FIRE_PREALARM, EXPIRED_PREALARM, CANCELLED_PREALARM, CONFIRMED_PREALARM, FIRE, FIRE_ENDED, AGENT_DEPLOYED_TO_INTERVENTION, AGENT_ARRIVED_AT_INTERVENTION, AGENT_LEFT_INTERVENTION, SMOKE_PRESENCE, NO_CARD_ENTRY, ROOM_EXIT, GATHERING_STARTED, GATHERING_ENDED
}
